[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200

# These dependencies will be automatically downloaded by PlatformIO when built!
lib_deps =
    mikalhart/TinyGPSPlus
    adafruit/Adafruit BNO055
    https://github.com/micro-ROS/micro_ros_platformio.git

# MicroROS build flag configuration
board_microros_transport = serial
build_flags = 
    -D uROS_TEENSY

# MicroROS library settings specific to teensy
lib_archive = false
